services:
  mcp-postgres-server:
    build:
      context: ./Backend/mcp-postgres-server
      dockerfile: Dockerfile
    container_name: mcp-postgres-server
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=ebp_dump
      - MCP_SERVER_NAME=ebp-postgres
      - MCP_SERVER_VERSION=1.0.0
      - NODE_ENV=development
      - LOG_LEVEL=info
    ports:
      - "3000:3000"
    networks:
      - ebp-network

volumes:
  postgres_sync_data:

networks:
  ebp-network:
    driver: bridge
